import { createHash } from 'node:crypto'

/** Files that are only useful to crawlers/social cards, or that must never be precached. */
const SKIP = /(^|\/)(og-image\.jpg|sitemap\.xml|robots\.txt|sw\.js)$|\.map$/

export interface PrecacheFile {
  /** Path relative to the build root, forward slashes ("assets/index-abc.js"). */
  name: string
  content: string | Uint8Array
}

export interface Precache {
  /** URLs relative to the service worker scope, sorted, "./" first. */
  urls: string[]
  /** Short hash of every precached file's name and bytes: changes whenever anything shipped changes. */
  version: string
}

/** Pure: which files get precached and the cache version derived from their content. */
export function buildPrecache(files: PrecacheFile[]): Precache {
  const kept = new Map<string, PrecacheFile>()
  for (const f of files) {
    const name = f.name.replace(/\\/g, '/').replace(/^\.?\//, '')
    if (name && !SKIP.test(name)) kept.set(name, { ...f, name })
  }
  const sorted = [...kept.values()].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  const h = createHash('sha256')
  for (const f of sorted) h.update(f.name).update('\0').update(f.content).update('\0')
  const urls = sorted.map((f) => f.name)
  if (kept.has('index.html')) urls.unshift('./') // the app shell is also served from the scope root
  return { urls, version: h.digest('hex').slice(0, 10) }
}

/** Service worker source. Every URL is resolved against registration.scope, so any sub-path works. */
export function renderServiceWorker({ urls, version }: Precache): string {
  return `// Generated by pwa-plugin.ts. Do not edit.
const VERSION = ${JSON.stringify(version)};
const PREFIX = 'webvna-';
const CACHE = PREFIX + VERSION;
const PRECACHE = ${JSON.stringify(urls, null, 2)};
const scope = self.registration.scope;
const abs = (u) => new URL(u, scope).href;
// ignoreVary: servers that send "Vary: Origin" (vite preview, some CDNs) would otherwise miss the cache for module scripts (CORS mode) while offline.

self.addEventListener('install', (event) => {
  // No skipWaiting here: the page asks for it (SKIP_WAITING) once the user agrees to reload.
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE.map((u) => new Request(abs(u), { cache: 'reload' })))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !req.url.startsWith(scope)) return;
  if (req.mode === 'navigate') {
    // Network first so a deploy shows up at once; the cached shell keeps the app working offline.
    event.respondWith(fetch(req).catch(() => caches.match(abs('index.html'), { cacheName: CACHE, ignoreVary: true }).then((r) => r || caches.match(abs('./'), { cacheName: CACHE, ignoreVary: true }))));
    return;
  }
  event.respondWith(caches.match(req, { cacheName: CACHE, ignoreVary: true }).then((hit) => hit || fetch(req)));
});
`
}
